/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author idaba
 */

public class StudentForm extends javax.swing.JFrame {
    private controller.StudentController controller = new controller.StudentController();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentForm.class.getName());

    /**
     * Creates new form StudentForm
     */
    public StudentForm() {
        initComponents();
        tampilkanDataKeTabel();
        controller.refreshTable(this); 
        txtNIK.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNIM = new javax.swing.JTextField();
        txtNIK = new javax.swing.JTextField();
        cmbProdi = new javax.swing.JComboBox<>();
        jbtnBatal = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jtxtCari = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel1.setText("MASTER STUDENT");
        jLabel1.setMinimumSize(new java.awt.Dimension(9, 16));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Data"));

        jLabel2.setText("Nama");

        jLabel3.setText("NIM");

        jLabel4.setText("NIK");

        jLabel5.setText("Prodi");

        txtNIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNIMKeyTyped(evt);
            }
        });

        txtNIK.setEditable(false);
        txtNIK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNIKKeyTyped(evt);
            }
        });

        cmbProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ilmu Komputer", "Pendidikan Teknik Mesin", "Pendidikan Teknik Informatika", "Sistem Informasi", "TRPL", " " }));

        jbtnBatal.setText("Cancel");
        jbtnBatal.addActionListener(this::jbtnBatalActionPerformed);

        jButton2.setForeground(new java.awt.Color(255, 51, 0));
        jButton2.setText("Delete");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        btnSave.addActionListener(this::btnSaveActionPerformed);

        jToggleButton1.setText("Back");
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNIK))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNIM))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBatal)
                    .addComponent(jButton2)
                    .addComponent(btnSave)
                    .addComponent(jToggleButton1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton4.setText("Cari");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIK", "Nama", "NIM", "Prodi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableStudent);

        jButton5.setText("Next >>");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("<< Prev");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton4)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // serahkan seluruh logika simpan, validasi digit, dan update otomatis ke controller
        controller.saveStudent(this);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // ambil baris tabel yang sedang dipilih oleh user
    int barisTerpilih = jTableStudent.getSelectedRow();

    // validasi apakah user sudah memilih baris atau belum
    if (barisTerpilih == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih data pada tabel terlebih dahulu!");
        return;
    }
    
    // konfirmasi dari user sebelum benar-benar menghapus
    int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menghapus data mahasiswa ini?", "Konfirmasi Hapus", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        // ambil NIK (id_card) dari kolom ke-0 (kolom pertama) pada baris yang diklik
        String idCard = jTableStudent.getValueAt(barisTerpilih, 0).toString();

        // panggil fungsi delete di studentdao
        dao.StudentDAO studentDao = new dao.StudentDAO();
        boolean sukses = studentDao.deleteStudent(idCard);

        // tampilkan notifikasi status
        if (sukses) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Mahasiswa Berhasil Dihapus!");

            // refresh tabel agar data yang dihapus langsung hilang dari layar
            tampilkanDataKeTabel();

            // kosongkan form input kembali
            txtNama.setText("");
            txtNIM.setText("");
            txtNIK.setText("");
            cmbProdi.setSelectedIndex(0);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Menghapus Data!");
        }
        
        txtNIK.setEditable(true);
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // ambil teks kata kunci dari kotak pencarian
    String kataKunci = jtxtCari.getText().trim();

    // kotak pencarian kosong, kembalikan tabel ke data default atau semua data
    if (kataKunci.isEmpty()) {
        tampilkanDataKeTabel();
        return;
    }

    // bersihkan isi tabel lama terlebih dahulu
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableStudent.getModel();
    model.setRowCount(0);

    // panggil fungsi search dari studentdao
    dao.StudentDAO studentDao = new dao.StudentDAO();
    java.util.List<String[]> hasilPencarian = studentDao.searchStudentByName(kataKunci);

    // masukkan hasil pencarian ke dalam komponen tabel
    if (hasilPencarian.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Data mahasiswa tidak ditemukan!");
        tampilkanDataKeTabel(); // tampilkan semua data kembali jika tidak ketemu
    } else {
        for (String[] data : hasilPencarian) {
            model.addRow(data);
        }
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBatalActionPerformed
        // mengosongkan kembali semua kotak input teks
        txtNama.setText("");
        txtNIM.setText("");
        txtNIK.setText("");

        // mengembalikan pilihan combobox prodi ke pilihan paling atas (-- Pilih Prodi --)
        cmbProdi.setSelectedIndex(0);

        // mengosongkan kotak pencarian jika ada isinya
        jtxtCari.setText("");

        // mengembalikan tampilan tabel ke data default semua data
        tampilkanDataKeTabel();

        // menaruh kursor fokus kembali ke kotak nik agar siap mengetik data baru
        txtNIK.requestFocus();

        // membuka kembali kunci kotak nik untuk data baru
        txtNIK.setEditable(true);
    }//GEN-LAST:event_jbtnBatalActionPerformed

    private void jTableStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStudentMouseClicked
    try {
        // ambil nomor baris tabel yang diklik
        int baris = jTableStudent.getSelectedRow();
        
        // validasi jika tidak ada baris yang terpilih
        if (baris == -1) {
            return;
        }

        // ambil data dari kolom tabel secara aman
        String nik   = jTableStudent.getValueAt(baris, 0) != null ? jTableStudent.getValueAt(baris, 0).toString() : "";
        String nama  = jTableStudent.getValueAt(baris, 1) != null ? jTableStudent.getValueAt(baris, 1).toString() : "";
        String nim   = jTableStudent.getValueAt(baris, 2) != null ? jTableStudent.getValueAt(baris, 2).toString() : "";
        String prodi = jTableStudent.getValueAt(baris, 3) != null ? jTableStudent.getValueAt(baris, 3).toString() : "";

        // paksa data masuk ke kotak input atas
        txtNIK.setText(nik);
        txtNama.setText(nama);
        txtNIM.setText(nim);
        cmbProdi.setSelectedItem(prodi);
        
        System.out.println("Berhasil klik tabel! Data NIK: " + nik); // untuk cek di panel output
        
        // mengunci kotak nik agar tidak bisa diubah-ubah saat edit
        txtNIK.setEditable(false);

    } catch (Exception e) {
        System.out.println("Gagal memindahkan data tabel: " + e.getMessage());
        }
    }//GEN-LAST:event_jTableStudentMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMouseClicked

    private void txtNIKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIKKeyTyped
    char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
                evt.consume(); // abaikan atau blokir jika yang diketik bukan angka
        }
    }//GEN-LAST:event_txtNIKKeyTyped

    private void txtNIMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIMKeyTyped
    char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNIMKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        controller.nextPage(this);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        controller.prevPage(this);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // membuat objek dashboardform baru
        view.DashboardForm dashboard = new view.DashboardForm();

        // menampilkan dashboard ke layar
        dashboard.setVisible(true);

        // mengatur posisi dashboard otomatis di tengah layar
        dashboard.setLocationRelativeTo(null);

        // menutup form agar hemat memori ram
        this.dispose(); 
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    // untuk memasukkan data dari dao ke dalam komponen jtable
    public void tampilkanDataKeTabel() {
        // Mengambil model tabel Anda yang bernama tableStudent
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableStudent.getModel();

        // bersihkan isi tabel lama agar tidak menumpuk ganda
        model.setRowCount(0);

        // panggil dao
        dao.StudentDAO studentDao = new dao.StudentDAO();
        java.util.List<String[]> listMahasiswa = studentDao.getAllStudents();

        // masukkan satu per satu baris data ke tabel
        for (String[] data : listMahasiswa) {
            model.addRow(data);
    }
}
    // kode getter manual untuk controller
    public javax.swing.JTextField getTxtNama() {
        return txtNama;
    }

    public javax.swing.JTextField getTxtNIM() {
        return txtNIM;
    }

    public javax.swing.JTextField getTxtNIK() {
        return txtNIK;
    }

    public javax.swing.JComboBox<String> getCmbProdi() {
        return cmbProdi;
    }

    public javax.swing.JTable getjTableStudent() {
        return jTableStudent; 
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbProdi;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStudent;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jbtnBatal;
    private javax.swing.JTextField jtxtCari;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
